name: "Regression Test - Docker Image"
on:
  workflow_dispatch:
  push:
env:
  TEST_TAG: ylt/ylt:test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup QEMU # used to allow multiplatform docker builds
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx # used to allow multiplatform docker builds
      uses: docker/setup-buildx-action@v3
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image # used to allow multiplatform docker builds
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        load: true
        tags: ${{ env.TEST_TAG }}
    - name: Check if webperf_core can run Test 17
      if: always()
      run: |
        docker run --shm-size=4g -e MAX_OLD_SPACE_SIZE=3000 ${{ env.TEST_TAG }} node node_modules/mocha/bin/mocha.js './test/core/**.js'
